# CONFIG
# dates based on ISO 8601 example: 1995-08-02 14:55:12

# Paths
path:
  css: "/css/"
  js: "/js/"
  pages: "/pages"

database:
  name: "symphony"
  user: "symphony"
  password: "password_symphony"
  host: "127.0.0.1"
  port: "33060"
  charset: "utf8"
  collate: "utf8_general_ci"

URL:
  prefix: "http"
  sub_domain: ""
  domain_name: "localhost"
  domain_extension: ""
  port: "8080"

HTML:
  lang: "en"
  charset: "utf-8"
  title: "Symphony"
